AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - lib/ods.rb
    - vendor/**/*
    - .bundle/**/*
Gemspec/RequiredRubyVersion:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Style/OptionalBooleanParameter:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Metrics:
  Exclude:
  - lib/bot/core/commands.rb
  - lib/bot/core/roles.rb
  - test/**/*
  - db/**/*
  - bin/**/*
Layout/LineLength:
  Exclude:
    - bin/*
Naming/MethodParameterName:
  AllowedNames: []
Metrics/BlockLength:
  Exclude:
    - 'commands/'
